package SemanticAnalysis;

public enum ErrorType {
    BOOLEAN_INT_CASTING,
    BOOLEAN_FLOAT_CASTING,
    BOOLEAN_CHAR_CASTING,
    INT_BOOLEAN_CASTING,
    INT_CHAR_CASTING,
    CHAR_FLOAT_CASTING,
    CHAR_BOOLEAN_CASTING,
    SINGLE_TO_ARRAY,
    ARRAY_TO_SINGLE,
    INVALID_CONDITION,
    NO_DECLARATION,
    MULTIPLE_DECLARATION,
    FLOAT_INT_CASTING,
    FLOAT_CHAR_CASTING,
    FLOAT_BOOLEAN_CASTING,

}
